server:
  port: 8082

spring:
  application:
    name: mis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mis?serverTimezone=GMT%2b8
    username: root
    password: 3271149877mm
#????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
